image:
  repository: 335448355144.dkr.ecr.ap-south-1.amazonaws.com/boni_chat
  tag: 5df8d01b15d58026e44ea3cbbe168f9a75aec816
  pullPolicy: IfNotPresent
autoscaling:
  apiVersion: autoscaling/v2
web:
  hpa:
    enabled: false
    cputhreshold: 75
    minpods: 1
    maxpods: 10
  replicaCount: 1
  resources: {}
worker:
  hpa:
    enabled: false
    cputhreshold: 75
    minpods: 2
    maxpods: 10
  replicaCount: 2
  resources: {}
services:
  name: chatwoot
  internalPort: 3000
  targetPort: 3000
  type: ClusterIP
  annotations: {}
imagePullSecrets:
  - name: aws-registry
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: ''
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: chatwoot
              port:
                number: 3000
  tls: []
nodeSelector: {}
tolerations: []
affinity: {}
postgresql:
  enabled: false
  nameOverride: chatwoot-postgresql
  auth:
    username: null
    postgresPassword: null
    database: null
  postgresqlHost: null
  postgresqlPort: 5432
redis:
  enabled: true
  nameOverride: chatwoot-redis
  auth:
    password: redis
  master:
    persistence:
      enabled: true
  replica:
    replicaCount: 1
hooks:
  affinity: {}
  migrate:
    env: []
    resources:
      limits:
        memory: 1000Mi
      requests:
        memory: 1000Mi
    hookAnnotation: pre-install,pre-upgrade
existingEnvSecret: ''
env:
  ACTIVE_STORAGE_SERVICE: local
  ANDROID_BUNDLE_ID: com.chatwoot.app
  ANDROID_SHA256_CERT_FINGERPRINT: AC:73:8E:DE:EB:56:EA:CC:10:87:02:A7:65:37:7B:38:D4:5D:D4:53:F8:3B:FB:D3:C6:28:64:1D:AA:08:1E:D8
  ASSET_CDN_HOST: ''
  AWS_ACCESS_KEY_ID: ''
  AWS_REGION: ''
  AWS_SECRET_ACCESS_KEY: ''
  ENABLE_ACCOUNT_SIGNUP: false
  FB_APP_ID: ''
  FB_APP_SECRET: ''
  FB_VERIFY_TOKEN: ''
  FORCE_SSL: false
  FRONTEND_URL: http://0.0.0.0:3000
  INSTALLATION_ENV: helm
  IOS_APP_ID: 6C953F3RX2.com.chatwoot.app
  LOG_LEVEL: info
  LOG_SIZE: 500
  MAILER_INBOUND_EMAIL_DOMAIN: ''
  MAILER_SENDER_EMAIL: ''
  MAILGUN_INGRESS_SIGNING_KEY: ''
  MANDRILL_INGRESS_API_KEY: ''
  RAILS_ENV: production
  RAILS_INBOUND_EMAIL_PASSWORD: ''
  RAILS_INBOUND_EMAIL_SERVICE: ''
  RAILS_LOG_TO_STDOUT: true
  RAILS_MAX_THREADS: 5
  REDIS_SENTINEL_MASTER_NAME: ''
  REDIS_SENTINELS: ''
  REDIS_TLS: false
  S3_BUCKET_NAME: ''
  SECRET_KEY_BASE: replace_with_your_super_duper_secret_key_base
  SENTRY_DSN: ''
  SLACK_CLIENT_ID: ''
  SLACK_CLIENT_SECRET: ''
  SMTP_ADDRESS: ''
  SMTP_AUTHENTICATION: plain
  SMTP_ENABLE_STARTTLS_AUTO: true
  SMTP_OPENSSL_VERIFY_MODE: none
  SMTP_PASSWORD: ''
  SMTP_PORT: 587
  SMTP_USERNAME: ''
  TWITTER_APP_ID: ''
  TWITTER_CONSUMER_KEY: ''
  TWITTER_CONSUMER_SECRET: ''
  TWITTER_ENVIRONMENT: ''
  USE_INBOX_AVATAR_FOR_BOT: true
